### ISSUE TITLE
Respect QGIS proxy settings

### ISSUE THREAD

**Issue by walkermatt** [AstunTechnology/QGIS-Gazetteer-Plugin#13]
Currently the plugin doesn't use the QGIS proxy settings which can cause requests to fail when a proxy server is required.

The plan is to use `QgsNetworkAccessManager` for requests which should respect the proxy settings.

## Testing

Work on the feature appears in the [proxy2 branch](https://github.com/AstunTechnology/QGIS-Gazetteer-Plugin/tree/proxy2). To test either [download the proxy2 zip](https://github.com/AstunTechnology/QGIS-Gazetteer-Plugin/archive/proxy2.zip) and follow the [manual installation instructions](https://github.com/AstunTechnology/QGIS-Gazetteer-Plugin#manual) or [clone the repo](https://github.com/AstunTechnology/QGIS-Gazetteer-Plugin#using-git) and checkout the proxy2 branch via `git checkout proxy2`.

**Comment by danblundell** [comment]
Running this as-is I get the following in QGIS error log and no search results, any ideas?
~~~
Traceback (most recent call last):
File "/Users/danblundell/.qgis2/python/plugins/gazetteersearch/gazetteers/common.py", line 51, in requestFinished
			    
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cgi.py", line 300, in parse_header

parts = _parseparam(';' + line)
TypeError: cannot concatenate 'str' and 'NoneType' objects
~~~

**Comment by walkermatt** [comment]
@danblundell it looks as though the content-type header isn't present. Which gazetteer are you searching? If it's not one of the standard gazetteers can you provide the URL if it's publicly accessible.

**Comment by danblundell** [comment]
@walkermatt our custom one and the geonames one both fail, if that's it, easy sorted

**Comment by walkermatt** [comment]
@danblundell have you configured the QGIS proxy settings and if so can you confirm that you are able to connect to other network resources such as adding a WMS layer?

I'll see about adding some more logging so we can more easily see what's happening.

**Comment by walkermatt** [comment]
@danblundell I've just pushed some changes to the [proxy2 branch](https://github.com/AstunTechnology/QGIS-Gazetteer-Plugin/tree/proxy2) which log any network errors in the "Gazetteer" Log Messages Panel. Let me know how you get on.

I've heard from another local authority user who was having issues using the Gazetteer behind a corporate proxy and they have been successful once they configured the QGIS proxy settings.

**Comment by walkermatt** [comment]
FYI I've now seen this version successfully tested within a local authority who had previously experienced issues due to the plugin not respecting proxy settings.

**Comment by walkermatt** [comment]
These changes have now been merged into `master`.
