### ISSUE TITLE
Changing plugin icon from default

### ISSUE THREAD

**Issue by mixedbredie** [AstunTechnology/QGIS-Gazetteer-Plugin#7]
One question: how do you change the plugin icon from the default "plug" to a bespoke one?

I have found a nice little "search" png file and have replaced the default icon.png with this but it does not change in the QGIS gui. Changing the name from "icon.png" to "search.png" and any references doesn't help either.

The new icon appears in the Plugin Manager but not on the toolbar.

I have changed references in metadata.txt, gazetteersearch.py

**Comment by ecotecnologias** [comment]
I'am new at it so could someone please explain how I can rerun the make file?
I have tried but it's saying that there is "nothing to be done by 'default' "

**Comment by walkermatt** [comment]
Hi, I think the make will only run if one of the files matched by a target has changed, try running `pyrcc -o resource_rc.py resource.qrc` as @NathanW2 suggests above.
